{% set version = "30.3.1" %}

package:
  name: license-expression
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/license-expression/license_expression-{{ version }}.tar.gz
  sha256: 60d5bec1f3364c256a92b9a08583d7ea933c7aa272c8d36d04144a89a3858c01

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - setuptools
    - python >=3.8
  run:
    - boolean.py >=4.0.0
    - python >=3.8

test:
  imports:
    - license_expression

about:
  home: https://github.com/nexB/license-expression
  license: Apache-2.0
  license_file:
    - NOTICE
    - apache-2.0.LICENSE
    - src/license_expression/_pyahocorasick.ABOUT
  summary: >
    license-expression is small utility library to parse, compare, simplify and normalize license expressions (such as SPDX license expressions) using boolean logic.
  doc_url: https://github.com/nexB/license-expression
  dev_url: https://github.com/nexB/license-expression

extra:
  recipe-maintainers:
    - xhochy
    - mbargull
