{% set version = "30.0.0" %}
{% set sha256 = "ad638292aa8493f84354909b517922cb823582c2ce2c4d880e42544a86bea8dd" %}

package:
  name: license-expression
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/license-expression/license-expression-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
  run:
    - boolean.py >=3.6,<4.0.0
    - python

test:
  imports:
    - license_expression

about:
  home: https://github.com/nexB/license-expression
  license: Apache-2.0
  license_file:
    - NOTICE
    - apache-2.0.LICENSE
    - src/license_expression/_pyahocorasick.ABOUT
  summary: >
    license-expression is small utility library to parse, compare, simplify and normalize license expressions (such as SPDX license expressions) using boolean logic.
  doc_url: https://github.com/nexB/license-expression
  dev_url: https://github.com/nexB/license-expression

extra:
  recipe-maintainers:
    - mbargull
