{% set version = "30.4.1" %}

package:
  name: license-expression
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/l/license-expression/license_expression-{{ version }}.tar.gz
  sha256: 9f02105f9e0fcecba6a85dfbbed7d94ea1c3a70cf23ddbfb5adf3438a6f6fce0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - boolean.py >=4.0.0
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - license_expression

about:
  home: https://github.com/nexB/license-expression
  license: Apache-2.0
  license_file:
    - NOTICE
    - apache-2.0.LICENSE
    - src/license_expression/_pyahocorasick.ABOUT
  summary: >
    license-expression is small utility library to parse, compare, simplify and normalize license expressions (such as SPDX license expressions) using boolean logic.
  doc_url: https://github.com/nexB/license-expression
  dev_url: https://github.com/nexB/license-expression

extra:
  recipe-maintainers:
    - xhochy
    - mbargull
