schema_version: 1

context:
  version: "30.4.3"

package:
  name: license-expression
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/l/license-expression/license_expression-${{ version }}.tar.gz
  sha256: 49f439fea91c4d1a642f9f2902b58db1d42396c5e331045f41ce50df9b40b1f2

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - setuptools
    - python ${{ python_min }}.*
  run:
    - boolean.py >=4.0.0
    - python >=${{ python_min }}

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - license_expression

about:
  license: Apache-2.0
  license_file:
    - NOTICE
    - apache-2.0.LICENSE
    - src/license_expression/_pyahocorasick.ABOUT
  summary: >
    license-expression is small utility library to parse, compare, simplify and normalize license expressions (such as SPDX license expressions) using boolean logic.
  homepage: https://github.com/nexB/license-expression
  repository: https://github.com/nexB/license-expression
  documentation: https://github.com/nexB/license-expression

extra:
  recipe-maintainers:
    - xhochy
    - mbargull
